package constants

const (
	BundleAuthenticationRequired   string = "AuthenticationRequired"
	BundleDocs                     string = "Docs"
	BundleDocsIntro                string = "DocsIntroduction"
	BundleEmail                    string = "Email"
	BundleForgotPasswordQuestion   string = "ForgotPasswordQuestion"
	BundleHome                     string = "Home"
	BundleHomeIntro                string = "HomeIntroduction"
	BundleInvalidEmailOrPassword   string = "InvalidEmailOrPassword"
	BundleJobs                     string = "Jobs"
	BundleJobsIntro                string = "JobsIntroduction"
	BundleLogin                    string = "Login"
	BundleLogout                   string = "Logout"
	BundleNavigateToHome           string = "NavigateToHome"
	BundleNavigateToLogin          string = "NavigateToLogin"
	BundleNotAuthenticatedTitle    string = "NotAuthenticatedTitle"
	BundlePageNotFound             string = "PageNotFound"
	BundlePageNotFoundTitle        string = "PageNotFoundTitle"
	BundlePassword                 string = "Password"
	BundlePlaylistFieldTitle       string = "PlaylistFieldTitle"
	BundlePlaylistFieldPlaceholder string = "PlaylistFieldPlaceholder"
	BundleProfile                  string = "Profile"
	BundleRegister                 string = "Register"
	BundleRegisterQuestion         string = "RegisterQuestion"
	BundleResetPassword            string = "ResetPassword"
	BundleSettings                 string = "Settings"
	BundleSubmit                   string = "Submit"
	BundleWelcome                  string = "Welcome"
)
